[package]
name = "pyflwdir-comparison"
version = "0.1.0"
edition = "2021"

[dependencies]
pyflwdir-rs = { path = "../pyflwdir-rs" }
ndarray = "0.15"
serde_json = "1.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort" 